export const fileValidation = {
  image: [
    "image/jpeg",
    "image/gif",
    "image/png",
    "image/tiff",
    "image/vnd.wap.wbmp",
    "image/x-ms-bmp",
    "application/octet-stream",
  ],
  document: [
    "application/msword",
    "application/pdf",
    "application/rss+xml",
    "application/vnd.google-earth.kml+xml",
    "application/vnd.google-earth.kmz",
    "application/vnd.ms-excel",
    "application/vnd.ms-powerpoint",
    "application/vnd.oasis.opendocument.presentation",
    "application/vnd.oasis.opendocument.spreadsheet",
    "application/vnd.oasis.opendocument.text",
    "application/vnd.sun.xml.calc",
    "application/vnd.sun.xml.writer",
    "application/x-gzip",
    "application/zip",
  ],
};
